// Dirección visual: Archivo operativo. Esta página convierte la investigación en un panel editorial legible y accionable.
import { useMemo, useState } from "react";
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Copy, ExternalLink, Mail, MessageSquare, ShieldCheck, Sparkles, Zap } from "lucide-react";

const models = [
  { id: "gpt-5-mini", label: "GPT-5 mini", note: "Recomendado", score: 92, price: "$0.25 / $2", fit: "Operativo", detail: "Rápido, con razonamiento, function calling y salidas estructuradas. Ideal para tareas bien definidas y alto volumen.", color: "amber" },
  { id: "gpt-5-nano", label: "GPT-5 nano", note: "Ultra ligero", score: 78, price: "$0.05 / $0.40", fit: "Clasificación", detail: "La alternativa de menor coste para etiquetar, extraer campos y enrutar conversaciones sencillas.", color: "green" },
  { id: "gemini-3-flash-preview", label: "Gemini 3 Flash", note: "Contexto largo", score: 86, price: "$0.50 / $3", fit: "Multimodal", detail: "Buena opción cuando el circuito necesita revisar documentos o entradas visuales con coste contenido.", color: "blue" },
];

const templates = {
  "Pregunta general": "Hola {{nombre}}, gracias por escribir a CIRCUIT. Para orientarte bien, necesito confirmar {{dato_faltante}}. En cuanto lo tenga, te indicaremos el siguiente paso más útil para tu caso.",
  "Solicitud de diagnóstico": "Hola {{nombre}}, por lo que nos cuentas, el mejor punto de partida es mapear el circuito de {{proceso}}. El diagnóstico permite detectar fricción, repetición y esperas antes de recomendar herramientas. ¿Te parece si concretamos una primera conversación?",
  "Petición de presupuesto": "Hola {{nombre}}, podemos preparar una estimación, pero preferimos no dar una cifra sin entender el alcance real. Necesitaríamos revisar {{alcance}} y confirmar {{restriccion}}. Después te enviaremos una propuesta clara, con fases y supuestos.",
  "Incidencia sensible": "Hola {{nombre}}, hemos recibido tu mensaje y lo estamos revisando con prioridad. Este caso requiere validación humana antes de confirmar una respuesta. Te escribiremos de nuevo en {{plazo}} con la información comprobada.",
  "Seguimiento": "Hola {{nombre}}, retomo el hilo sobre {{tema}}. La última decisión pendiente era {{pendiente}}. Si sigue siendo prioritario, puedo dejar preparado el siguiente paso y coordinarlo contigo.",
};

const sections = ["Resumen", "Modelo", "Circuito", "Plantillas", "Guardrails"];

export default function Home() {
  const [activeSection, setActiveSection] = useState("Resumen");
  const [activeModel, setActiveModel] = useState(models[0].id);
  const [channel, setChannel] = useState<"chat" | "email">("chat");
  const [template, setTemplate] = useState<keyof typeof templates>("Pregunta general");
  const [copied, setCopied] = useState(false);
  const selected = useMemo(() => models.find((model) => model.id === activeModel) ?? models[0], [activeModel]);

  const copyTemplate = async () => {
    await navigator.clipboard?.writeText(templates[template]);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  };

  return (
    <div className="min-h-screen bg-[#0b0c0c] text-[#f5f3ef] selection:bg-[#e8a838] selection:text-[#0b0c0c]">
      <aside className="fixed inset-y-0 left-0 z-20 hidden w-[250px] border-r border-white/10 bg-[#0b0c0c]/95 p-6 lg:flex lg:flex-col">
        <a href="#top" className="flex items-center gap-3 text-sm font-semibold tracking-[0.24em]"><img src="/manus-storage/circuit-node-logo_6e0af8a2.png" alt="Símbolo CIRCUIT" className="size-8 object-contain" /> CIRCUIT</a>
        <div className="mt-14 font-mono text-[10px] uppercase tracking-[0.2em] text-white/35">Informe / 001</div>
        <nav className="mt-6 space-y-1" aria-label="Secciones del informe">
          {sections.map((section, index) => <a key={section} href={`#${section.toLowerCase()}`} onClick={() => setActiveSection(section)} className={`group flex items-center gap-3 py-3 text-sm transition-colors ${activeSection === section ? "text-[#e8a838]" : "text-white/50 hover:text-white"}`}><span className={`font-mono text-[10px] ${activeSection === section ? "text-[#e8a838]" : "text-white/25"}`}>0{index + 1}</span><span className="h-px w-5 bg-current opacity-40 transition-all group-hover:w-8" />{section}</a>)}
        </nav>
        <div className="mt-auto border-t border-white/10 pt-5 font-mono text-[10px] leading-relaxed text-white/35">RESEARCH SNAPSHOT<br />28 AGO 2026<br /><span className="text-[#34d399]">● FUENTES VERIFICADAS</span></div>
      </aside>

      <main id="top" className="lg:pl-[250px]">
        <header className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#0b0c0c]/90 px-5 py-4 backdrop-blur-xl lg:px-12"><div className="flex items-center gap-3 lg:hidden"><img src="/manus-storage/circuit-node-logo_6e0af8a2.png" alt="Símbolo CIRCUIT" className="size-7 object-contain" /><span className="text-xs font-semibold tracking-[0.22em]">CIRCUIT</span></div><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/45">AI Support / Research brief</div><div className="flex items-center gap-2 text-[11px] text-[#34d399]"><span className="size-1.5 rounded-full bg-[#34d399]" /> Propuesta conceptual</div></header>

        <section className="relative overflow-hidden border-b border-white/10 px-5 pb-20 pt-16 lg:px-16 lg:pb-28 lg:pt-24"><div className="absolute inset-0 -z-0 bg-[url('/manus-storage/circuit-archive-texture_8b613af9.png')] bg-cover bg-center opacity-40" /><div className="absolute inset-0 -z-0 bg-gradient-to-r from-[#0b0c0c] via-[#0b0c0c]/85 to-transparent" /><div className="relative z-1 max-w-5xl"><div className="mb-8 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#e8a838]"><span className="h-px w-9 bg-[#e8a838]" /> Investigación aplicada / CIRCUIT OS</div><h1 className="max-w-4xl text-[clamp(3.5rem,8vw,8.5rem)] font-semibold leading-[0.87] tracking-[-0.07em]">Responde rápido.<br /><span className="text-white/35">Decide con criterio.</span></h1><div className="mt-12 grid max-w-4xl gap-8 lg:grid-cols-[1.25fr_0.75fr]"><p className="max-w-xl text-lg leading-relaxed text-white/65">Un modelo compacto y robusto para conversar con clientes como una persona, preparar respuestas de correo y mantener cada decisión dentro de un circuito revisable.</p><div className="border-l border-[#e8a838] pl-5 font-mono text-xs leading-relaxed text-white/55">RECOMENDACIÓN BASE<br /><strong className="text-base font-medium text-[#e8a838]">GPT-5 mini</strong><br />+ conocimiento aprobado<br />+ revisión humana</div></div></div></section>

        <section id="resumen" className="border-b border-white/10 px-5 py-16 lg:px-16 lg:py-24"><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><div className="eyebrow">01 / Resumen ejecutivo</div><h2 className="mt-5 max-w-md text-4xl font-semibold leading-tight tracking-[-0.04em]">La IA no es el producto. Es el tramo asistido del circuito.</h2><p className="mt-6 max-w-md leading-relaxed text-white/55">La solución propuesta separa lo que puede ser rápido y repetible de lo que requiere criterio. El asistente sugiere; CIRCUIT decide qué se envía.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-3"><Metric value="400k" label="contexto del modelo" source="ficha oficial" /><Metric value="3 capas" label="modelo · contexto · revisión" source="arquitectura" /><Metric value="2 canales" label="chat web + email" source="alcance inicial" /></div></div></section>

        <section id="modelo" className="border-b border-white/10 px-5 py-16 lg:px-16 lg:py-24"><div className="eyebrow">02 / Selección del modelo</div><div className="mt-5 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-semibold leading-tight tracking-[-0.04em]">Un núcleo ligero para lo frecuente. Un escalado claro para lo difícil.</h2><span className="font-mono text-[10px] text-white/40">INPUT / OUTPUT · USD POR 1M TOKENS</span></div><div className="mt-10 overflow-hidden border-y border-white/10"><div className="hidden grid-cols-[1.2fr_.8fr_.8fr_1fr] gap-4 bg-white/[.04] px-5 py-3 font-mono text-[9px] uppercase tracking-[.15em] text-white/35 sm:grid"><span>Modelo / función</span><span>Coste</span><span>Encaje</span><span>Lectura CIRCUIT</span></div>{models.map((model, index) => <button key={model.id} onClick={() => setActiveModel(model.id)} className={`grid w-full gap-3 border-b border-white/10 px-5 py-5 text-left transition-all last:border-0 sm:grid-cols-[1.2fr_.8fr_.8fr_1fr] sm:items-center ${activeModel === model.id ? "bg-[#f5f3ef] text-[#0b0c0c]" : "text-white hover:bg-white/[.04]"}`}><span className="flex items-center gap-3"><span className="font-mono text-[10px] opacity-40">0{index + 1}</span><span><strong className="block text-lg font-medium">{model.label}</strong><small className="font-mono text-[10px] uppercase opacity-50">{model.note} · {model.fit}</small></span></span><span className="font-mono text-xs opacity-70">{model.price}</span><span><span className="block font-mono text-sm text-[#e8a838]">{model.score}/100</span><span className="mt-2 block h-1 bg-current/10"><span className={`block h-full ${model.color === "amber" ? "bg-[#e8a838]" : model.color === "green" ? "bg-[#34d399]" : "bg-[#83a7c7]"}`} style={{ width: `${model.score}%` }} /></span></span><span className="text-sm leading-relaxed opacity-60">{model.detail}</span></button>)}</div><div className="mt-5 grid gap-8 border-t border-white/10 pt-6 lg:grid-cols-[1fr_0.65fr]"><div className="font-mono text-[10px] uppercase tracking-[0.14em] text-white/30">FICHA / 02<br />Criterio de selección<br />No es una verdad científica.</div><p className="max-w-2xl text-sm leading-relaxed text-white/60">{selected.detail} Para CIRCUIT, la recomendación es comenzar con prompts precisos y salidas estructuradas; no hace falta fine-tuning para el primer circuito.</p><div className="flex items-start gap-3 font-mono text-[10px] uppercase leading-relaxed text-[#34d399]"><Check className="mt-0.5 size-4 shrink-0" /> La ficha oficial confirma herramientas, visión y structured outputs.</div></div></section>

        <section id="circuito" className="border-b border-white/10 px-5 py-16 lg:px-16 lg:py-24"><div className="eyebrow">03 / Arquitectura del circuito</div><div className="mt-10 grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="relative pl-8"><div className="absolute bottom-3 left-2 top-3 w-px bg-gradient-to-b from-[#e8a838] via-[#e8a838] to-[#34d399]" />{[{n:"01",title:"Entra",desc:"Chat web o nuevo correo."},{n:"02",title:"Entiende",desc:"Intención, urgencia, idioma y campos."},{n:"03",title:"Consulta",desc:"Base de conocimiento aprobada."},{n:"04",title:"Propone",desc:"Respuesta con confianza y fuentes."},{n:"05",title:"Revisa",desc:"Humano aprueba, edita o escala."}].map((step) => <div key={step.n} className="relative mb-8 last:mb-0"><span className="absolute -left-[31px] grid size-5 place-items-center rounded-full border border-[#e8a838] bg-[#0b0c0c] font-mono text-[8px] text-[#e8a838]">{step.n}</span><h3 className="text-xl font-medium">{step.title}</h3><p className="mt-1 text-sm text-white/45">{step.desc}</p></div>)}</div><div className="overflow-hidden bg-[#141615]"><img src="/manus-storage/circuit-conversation-illustration_c2719bdd.png" alt="Diagrama editorial del circuito de una conversación" className="h-52 w-full object-cover opacity-90" /><div className="grid gap-0 border-t border-white/10 sm:grid-cols-2"><div className="p-6"><div className="flex items-center gap-2 font-mono text-[10px] uppercase text-[#e8a838]"><MessageSquare className="size-3" /> Chat web</div><p className="mt-4 text-sm leading-relaxed text-white/55">Respuestas en tiempo real para preguntas frecuentes, orientación inicial y captura de contexto.</p></div><div className="border-t border-white/10 p-6 sm:border-l sm:border-t-0"><div className="flex items-center gap-2 font-mono text-[10px] uppercase text-[#e8a838]"><Mail className="size-3" /> Correo</div><p className="mt-4 text-sm leading-relaxed text-white/55">Gmail API + notificación push para preparar borradores sin polling continuo.</p></div></div></div></div></section>

        <section id="plantillas" className="border-b border-white/10 px-5 py-16 lg:px-16 lg:py-24"><div className="eyebrow">04 / Biblioteca de plantillas</div><div className="mt-5 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-semibold leading-tight tracking-[-0.04em]">Todas las respuestas empiezan con un patrón revisable.</h2><div className="flex border border-white/10 p-1"><button onClick={() => setChannel("chat")} className={`flex items-center gap-2 px-3 py-2 text-xs ${channel === "chat" ? "bg-[#e8a838] text-[#0b0c0c]" : "text-white/50"}`}><MessageSquare className="size-3" /> Chat</button><button onClick={() => setChannel("email")} className={`flex items-center gap-2 px-3 py-2 text-xs ${channel === "email" ? "bg-[#e8a838] text-[#0b0c0c]" : "text-white/50"}`}><Mail className="size-3" /> Email</button></div></div><div className="mt-10 grid gap-4 lg:grid-cols-[0.72fr_1.28fr]"><div className="space-y-1">{Object.keys(templates).map((name) => <button key={name} onClick={() => setTemplate(name as keyof typeof templates)} className={`flex w-full items-center justify-between border-b border-white/10 px-4 py-4 text-left text-sm transition-colors ${template === name ? "bg-[#e8a838] text-[#0b0c0c]" : "text-white/60 hover:bg-white/5 hover:text-white"}`}>{name}<ChevronRight className="size-4" /></button>)}</div><div className="bg-[#f5f3ef] p-6 text-[#0b0c0c] lg:p-8"><div className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.14em] text-black/45"><span>{channel === "chat" ? "Borrador para chat" : "Borrador para email"}</span><span className="text-[#a96d12]">Revisión necesaria</span></div><div className="mt-10 max-w-xl text-xl leading-relaxed">{templates[template]}</div><div className="mt-10 flex items-center justify-between border-t border-black/10 pt-4"><span className="flex items-center gap-2 text-xs text-black/50"><ShieldCheck className="size-4 text-[#34a979]" /> Sin envío automático</span><button onClick={copyTemplate} className="flex items-center gap-2 bg-[#0b0c0c] px-3 py-2 text-xs text-white transition-transform active:scale-95">{copied ? <Check className="size-3" /> : <Copy className="size-3" />}{copied ? "Copiado" : "Copiar plantilla"}</button></div></div></div></section>

        <section id="guardrails" className="border-b border-white/10 px-5 py-16 lg:px-16 lg:py-24"><div className="eyebrow">05 / Guardrails de confianza</div><div className="mt-5 grid gap-10 lg:grid-cols-[1fr_1fr]"><h2 className="max-w-xl text-4xl font-semibold leading-tight tracking-[-0.04em]">Humano donde importa. Transparente siempre.</h2><div className="space-y-5">{[{icon:ShieldCheck,title:"Revisión humana",text:"Contratos, precios, incidencias y mensajes sensibles quedan en cola de aprobación."},{icon:CircleHelp,title:"Incertidumbre explícita",text:"Si la base no contiene una respuesta fiable, el sistema pregunta o escala; no rellena huecos."},{icon:Zap,title:"Memoria controlada",text:"Solo usa contexto necesario, con retención y permisos definidos por el negocio."}].map(({icon:Icon,title,text}) => <div key={title} className="flex gap-4 border-t border-white/10 pt-5"><Icon className="mt-1 size-5 shrink-0 text-[#e8a838]" /><div><h3 className="font-medium">{title}</h3><p className="mt-1 text-sm leading-relaxed text-white/50">{text}</p></div></div>)}</div></div></section>

        <section className="px-5 py-16 lg:px-16 lg:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><div className="eyebrow">Conclusión</div><h2 className="mt-5 max-w-2xl text-5xl font-semibold leading-[0.95] tracking-[-0.05em]">Un buen asistente no parece mágico. Parece bien diseñado.</h2><p className="mt-6 max-w-xl leading-relaxed text-white/55">La primera versión debería medir precisión, escalados, tiempo de respuesta y correcciones humanas antes de automatizar el envío. El circuito gana valor cuando cada respuesta deja una señal que se puede mejorar.</p></div><div className="border border-[#e8a838]/50 p-6"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-[#e8a838]"><Sparkles className="size-3" /> Próximo paso</div><p className="mt-5 text-2xl font-medium leading-tight">Construir el primer circuito con 20 preguntas reales y 5 plantillas aprobadas.</p><a href="#plantillas" className="mt-8 inline-flex items-center gap-2 text-sm text-white underline decoration-[#e8a838] underline-offset-4">Revisar plantillas <ArrowUpRight className="size-4" /></a></div></div><div className="mt-20 border-t border-white/10 pt-6"><div className="eyebrow">Fuentes consultadas</div><div className="mt-5 grid gap-3 text-xs text-white/45 sm:grid-cols-3"><a className="flex items-center justify-between border-b border-white/10 py-3 hover:text-white" href="https://developers.openai.com/api/docs/models/gpt-5-mini" target="_blank" rel="noreferrer">[1] OpenAI / GPT-5 mini <ExternalLink className="size-3" /></a><a className="flex items-center justify-between border-b border-white/10 py-3 hover:text-white" href="https://developers.google.com/workspace/gmail/api/guides/push" target="_blank" rel="noreferrer">[2] Google / Gmail push <ExternalLink className="size-3" /></a><a className="flex items-center justify-between border-b border-white/10 py-3 hover:text-white" href="https://www.edpb.europa.eu/topics/artificial-intelligence_en" target="_blank" rel="noreferrer">[3] EDPB / IA y datos <ExternalLink className="size-3" /></a></div></div></section>
        <footer className="flex flex-col justify-between gap-4 border-t border-white/10 px-5 py-8 font-mono text-[10px] uppercase tracking-[0.14em] text-white/35 sm:flex-row lg:px-16"><span>CIRCUIT · Modernización de operaciones</span><span>La tecnología se adapta al trabajo.</span></footer>
      </main>
    </div>
  );
}

function Metric({ value, label, source }: { value: string; label: string; source: string }) { return <div className="bg-[#141615] p-5"><div className="text-3xl font-semibold tracking-[-0.05em] text-[#e8a838]">{value}</div><div className="mt-2 text-xs text-white/60">{label}</div><div className="mt-6 font-mono text-[9px] uppercase text-white/25">{source}</div></div>; }
